version: '3'

services:
  tts-service:
    build: .
    image: ghcr.io/coqui-ai/tts
    container_name: coqui-tts
    entrypoint: ["/bin/bash", "-c"]
    command: ["while true; do sleep 3600; done"]
    ports:
      - "5002:5002"
    volumes:
      - ./voice_samples:/app/voice_samples
      - ./models:/app/models
      - ./server:/app/server
      - ./output:/app/output
      - ./custom:/app/custom
    restart: unless-stopped
